language: php
php:
 - 5.5

install:
 - echo "yes\n" | pecl install pecl_http
 - echo "extension=raphf.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
 - composer install --prefer-dist --dev
 - npm install -g grunt-cli
 - npm install

script: grunt test