language: php
php:
 - 5.5

install:
 - echo "yes\n" | pecl install pecl_http
 - cat ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini | grep -v '^;'
 - composer install --prefer-dist --dev
 - npm install -g grunt-cli
 - npm install

script: grunt test