language: php
php:
 - '5.6'
 - '5.5'
 - hhvm

matrix:
  allow_failures:
    - php: '5.6'
    - php: hhvm

cache:
  directories:
    - vendor
    - node_modules

env:
  global:
   - secure: mo27nTmvQ4Gxrp5Wxqp1X2/G7JRTJxljBVGpEQHhgwkyZsdRYuO+kALJRxeV6k6/6mND6FZnONzzCGzKmMCgH5/8fI/Xpox+RuqUG03L8P0yjIrl6azk/gXsZUoP1/yUKmMFJsAknJUeDNMt7NDZnfuvgHRZowawdqVPklBvIjI=

install:
 - sudo apt-get install graphviz
 - composer install --prefer-dist --dev
 - npm install -g grunt-cli
 - npm install

after_success:
 - php vendor/bin/coveralls
 - grunt docs
