language: php
php:
 - 5.5

install:
 - echo "yes\n" | pecl install pecl_http
 - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/http.ini ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/zzz-http.ini
 - composer install --prefer-dist --dev
 - npm install -g grunt-cli
 - npm install

script: grunt test